#!/bin/bash
set -e

die() {
  echo "$@" >&2
  exit 1
}

# beacuse OSX is shit and can't do `readlink -f`
readlink_() {
  local src="${BASH_SOURCE[0]}"
  while [ -h "$src" ]; do
    local dir="$(cd -P "$( dirname "$src" )" && pwd)"
    local src="$(readlink "$src")"
    [[ $src != /* ]] && src="$dir/$src"
  done
  echo "$(cd -P "$( dirname "$src" )" && pwd)"
}

node_deb_dir=`readlink_ $0`

# All the variables that are injected into templates
package_name=
package_version=
executable_name=
start_command=
user=
group=
package_description=
package_maintainer=

# Other variables
change_log=
files=
no_delete_temp=0
no_md5sums=0

usage() {
  # Local var because of grep
  local helpdoc='HELP'
  local helpdoc+='DOC'
  echo 'Usage: node-deb [opts] -- file1 file2 ...'
  echo 'Opts:'
  grep "$helpdoc" "$node_deb_dir/node-deb" -B 1 | egrep -v '^--$' | sed -e 's/^  //g' -e "s/# $helpdoc: //g"
}

zero_check() {
  if [ -z "$1" ]; then
    die "Cannot pass zero length string to option $2"
  fi
}

while [ -n "$1" ]; do
  param="$1"
  value="$2"
  case $param in
    -d | --description)
      # HELPDOC:  The description of the Debian package (default: 'node_deb.description' then 'description' from package.json)
      zero_check $value $param
      package_description="$value"
      shift
      ;;
    -e | --executable-name)
      # HELPDOC: The name of the executable (default: 'node_deb.executable_name' then $package-name)
      zero_check $value $param
      executable_name="$value"
      shift
      ;;
    -g | --group)
      # HELPDOC:  The Unix group the process will run as (default: 'node_deb.group' then $user)
      zero_check $value $param
      group="$value"
      shift
      ;;
    -h | --help)
      # HELPDOC: Display this message and exit
      usage
      exit 0
      ;;
    -m | --maintainer)
      # HELPDOC: The maintainer of the Debian package (default: 'node_deb.maintainer' then 'author' from package.json)
      zero_check $value $param
      package_maintainer="$value"
      shift
      ;;
    -n | --package-name)
      # HELPDOC: The name of the Debian package (default: 'node_deb.package_name' then 'name' from package.json)
      zero_check $value $param
      package_name="$value"
      shift
      ;;
    --no-delete-temp)
      # HELPDOC: Do not delete temp directory used to build Debian package
      no_delete_temp=1
      ;;
    --no-md5sums)
      # HELPDOC: Do not calculate md5sums for DEBIAN directory
      no_md5sums=1
      ;;
    -u | --user)
      # HELPDOC: The Unix user the process will run as (default: 'node_deb.user' then $package-name)
      zero_check $value $param
      user="$value"
      shift
      ;;
    -v | --version)
      # HELPDOC: The version of the Debian package (default: 'node_deb.version' then 'version' from package.json)
      zero_check $value $param
      package_version="$value"
      shift
      ;;
    --)
      # HELPDOC: Delimiter separating options from files and directories
      shift
      break
      ;;
    *)
      echo "Invalid option: $param" >&2
      usage >&2
      exit 1
  esac
  shift
done

if [ -z "$1 " ]; then
  die 'You must pick at least one file or directory to add to the Debian package'
fi

for file in $files; do
  if ! [ -e $file ]; then
    die "File does not exist: '$file'. Aborting"
  fi
done

set_package_name() {
  if [ -z "$package_name" ]; then
    package_name=`jq -r '.node_deb.package_name' package.json`
    if [[ "$package_name" == 'null' ]]; then
      package_name=`jq -r '.name' package.json`
      if [ "$package_name" == 'null' ]; then 
        die 'If no override is provided, your package.json must have element "node_deb.package_name" or "name"'
      fi
    fi
  fi
}

set_start_command() {
  start_command=`jq -r '.node_deb.start_command' package.json`
  if [ "$start_command" == 'null' ]; then
    die 'Your package.json must have element "node_deb.start_command"'
  fi
}

set_package_version() {
  if [ -z "$package_version" ]; then
    package_version=`jq -r '.node_deb.version' package.json`
    if [[ "$package_version" == 'null' ]]; then
      package_version=`jq -r '.version' package.json`
      if [ "$package_version" == 'null' ]; then
        die 'If no override is provided, your package.json must have element "node_deb.package_version" "version"'
      fi
    fi
  fi
}

set_executable_name() {
  if [ -z "$executable_name" ]; then
    executable_name=`jq -r '.node_deb.executable_name' package.json`
    if [[ "$executable_name" == 'null' ]]; then
      executable_name="$package_name"
    fi
  fi
}

set_user() {
  if [ -z "$user" ]; then
    user=`jq -r '.node_deb.user' package.json`
    if [[ "$user" == 'null' ]]; then
      user="$package_name"
    fi
  fi
}

set_group() {
  if [ -z "$group" ]; then
    group=`jq -r '.node_deb.group' package.json`
    if [[ "$group" == 'null' ]]; then
      group="$user"
    fi
  fi
}

set_package_description() {
  if [ -z "$package_description" ]; then
    package_description=`jq -r '.node_deb.description' package.json`
    if [[ "$package_description" == 'null' ]]; then
      package_description=`jq -r '.description' package.json`
      if [[ "$package_description" == null ]]; then
        die 'If no override is provided, your package.json must have element "node_deb.package_description" or "description"'
      fi
    fi
  fi
}

set_package_maintainer() {
  if [ -z "$package_maintainer" ]; then
    package_maintainer=`jq -r '.node_deb.maintainer' package.json`
    if [[ "$package_maintainer" == 'null' ]]; then
      package_maintainer=`jq -r '.author' package.json`
    fi
  fi
}

set_package_name
set_package_version
set_package_description
set_package_maintainer
set_executable_name
set_start_command
set_user
set_group

deb_dir="${package_name}_${package_version}_all"

finish() {
  if [ $no_delete_temp -ne 1 ]; then
    rm -rf "$deb_dir"
  fi
}

trap "finish" EXIT

if [ -e "$deb_dir" ]; then rm -rf "$deb_dir"; fi

mkdir -p "$deb_dir/DEBIAN"
mkdir -p "$deb_dir/etc/$package_name"
mkdir -p "$deb_dir/etc/init"
mkdir -p "$deb_dir/usr/share/$package_name/bin"
mkdir -p "$deb_dir/usr/bin"

escape() {
  sed -e 's/[]\/$*.^|[]/\\&/g' <<< "$@"
}

replace_vars() {
  local file="$1"
  local target_file="$2"

  sed < $file \
    -e "s/\${node_deb_package_name}/$(escape $package_name)/g" \
    -e "s/\${node_deb_app_command}/$(escape $app_command)/g" \
    -e "s/\${node_deb_package_version}/$(escape $package_version)/g" \
    -e "s/\${node_deb_start_command}/$(escape $start_command)/g" \
    -e "s/\${node_deb_package_description}/$(escape $package_description)/g" \
    -e "s/\${node_deb_group}/$(escape $group)/g" \
    -e "s/\${node_deb_package_maintainer}/$(escape $package_maintainer)/g" \
    -e "s/\${node_deb_user}/$(escape $user)/g" \
    > $target_file
}

replace_vars "$node_deb_dir/templates/control" "$deb_dir/DEBIAN/control"
replace_vars "$node_deb_dir/templates/postinst" "$deb_dir/DEBIAN/postinst"
replace_vars "$node_deb_dir/templates/postrm" "$deb_dir/DEBIAN/postrm"
replace_vars "$node_deb_dir/templates/prerm" "$deb_dir/DEBIAN/prerm"
replace_vars "$node_deb_dir/templates/init.conf" "$deb_dir/etc/init/$package_name.conf"
replace_vars "$node_deb_dir/templates/executable" "$deb_dir/usr/share/$package_name/bin/$executable_name"

ln -sf "/usr/share/$node_app/bin/$executable_name" "$deb_dir/usr/bin/$executable_name"

chmod -R 0755 "$deb_dir/DEBIAN/"
chmod -R 0755 "$deb_dir/usr/share/$package_name/bin/$executable_name"

# Copy all files into temporary Debian dir
find "$@" -type f -print0 | {
  while IFS= read -r -d '' file; do
    dir="$deb_dir/usr/share/$package_name/$(dirname "$file")"
    if ! [ -e "$dir" ]; then mkdir -p "$dir"; fi
    cp "$file" "$dir"
  done
}

write_md5sum() {
  # Using $@ and not $1 because of files with whitespace
  local file="$@"

  # Debian/Ubuntu
  if hash md5sum 2>/dev/null; then
    local sum=`md5sum "$file" | cut -d ' ' -f1`
  # OSX
  elif hash md5 2>/dev/null; then
    local sum=`md5 "$file" | awk -F '=' '{ printf $NF }' | tr -d ' '`
  # Oh dear...
  else
    die 'Unable to find suitable md5 sum program'
  fi

  local file=`echo $file | sed -e "s/$(escape $deb_dir)//" | sed -e 's:^\.::' -e 's:^/*::'`
  echo "$sum $file" >> "$deb_dir/DEBIAN/md5sums"
}

# Calculate md5sums
if [ "$no_md5sums" -eq 0 ]; then
  find "$deb_dir" -path "$deb_dir/DEBIAN" -prune -o -type f -print0 | {
  while IFS= read -r -d '' file; do
    write_md5sum "$file"
  done
}
fi

dpkg-deb --build "$deb_dir"
